# Generated by Django 3.1.2 on 2020-10-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asteroids', '0004_auto_20201010_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asteroidregistration',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
