# Generated by Django 3.1.2 on 2020-10-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asteroids', '0005_auto_20201010_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asteroidregistration',
            name='matrix',
        ),
        migrations.AddField(
            model_name='asteroidregistration',
            name='height',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asteroidregistration',
            name='width',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
